---
title: "Testes RU -- Parte II"
author: "R Ballini"
date: "28/03/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Taxa de Câmbio
```{r}
library(readxl)

cambio=read_excel('Cambio.xlsx')

cambio = ts(cambio[,2],start=c(2000,1),freq=12)

plot(cambio,ylab='Taxa de Câmbio', main='Taxa de Câmbio R$/US$')
acf(cambio,main='Taxa de Câmbio R$/US$')

```

## Teste de Dickey-Pantula

```{r}
#install.packages('dynlm')
library(dynlm)

#Passo 1: Teste para 2 RU
etapa1=dynlm(diff(log(cambio),1,2)~trend(cambio,scale=F)+diff(L(log(cambio)),1,1))
summary(etapa1)

acf(etapa1$residuals,type='correlation')
acf(etapa1$residuals,type='partial')

etapa1=dynlm(diff(log(cambio),1,2)~diff(L(log(cambio)),1,1))
summary(etapa1)

acf(etapa1$residuals,type='correlation')
acf(etapa1$residuals,type='partial')

etapa1=dynlm(diff(log(cambio),1,2)~diff(L(log(cambio)),1,1)-1)
summary(etapa1)

acf(etapa1$residuals,type='correlation')
acf(etapa1$residuals,type='partial')


#Etapa 2: Teste para 1 RU
etapa2=dynlm(diff(log(cambio),1,2)~diff(L(log(cambio)),1,1)+L(log(cambio)))
summary(etapa2)

acf(etapa2$residuals,type='correlation')
acf(etapa2$residuals,type='partial')
```


# Teste de Raiz Unitária Sazonal

```{r}

pib=read_excel('PIB_Agropecuaria.xlsx')
pib=ts(pib[,2],start=c(1996,1),freq=4)

#install.packages('urca')
library(urca)

install.packages('uroot')
library(uroot)

#deterministic = a vector of length three containing zeros or ones to indicate, respectively, whether a constant, a trend or seasonal dummies are included in the regression equation of the test.
sazonal.ur=hegy.test(pib, deterministic = c(1,1,1), lag.method = "fixed", maxlag = 1)

sazonal.ur=hegy.test(pib,deterministic = c(1,1,1), lag.method = "BIC", maxlag = 12)
sazonal.ur$fitted.model
sazonal.ur$statistics
sazonal.ur$pvalues

#Teste DHF
#Instalando e carregando pacote de Dummies sazonais
install.packages("gets")
library(gets)

teste.sazonal=dynlm(diff(pib,1,4)~trend(pib,scale=F)+ season(pib) + L(pib,4)+diff(L(pib,1:4),1,12))
summary(teste.sazonal)         
acf(teste.sazonal$residuals)
pacf(teste.sazonal$residuals)


```

